title: My Portfolio
name: Deja van Alphen-Santoro
email: dejavasart@gmail.com
baseurl: /Portfolio/
#url: https://dejavasart.github.io/Portfolio/

instagram: https://www.instagram.com/dvas.art
linkedin: https://www.linkedin.com/in/dejavas/